spring:
  cloud:
    config:
      enabled: false
  jpa:
    generate-ddl: 'false'
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        search:
          backend:
            analysis:
              configurer: ru.clevertec.news.search.LuceneConfig
            directory:
              root: src\main\resources\db\index
  datasource:
    password: admin
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/nms_news_service
  main:
    allow-circular-references: true

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

cache:
  algorithm: LRU
  capacity: 6

aop:
  logging:
    enabled: true

exception:
  handling:
    enabled: false